### ISSUE TITLE
3rd Party Certificates

### ISSUE THREAD

**Issue by andyjhall** [morph1904/TygerCaddy#103]
Could there be an option to use third party certificates, for example Alexa webservice give you a certificate to use rather than allowing you to generate one via lets encrypt.

**Comment by morph1904** [comment]
@andyjhall This is scheduled for the next release, we will add text boxes to add certificate strings for now and then look at file uploads later.

**Comment by morph1904** [comment]
@andyjhall We have a working version of this in the custom SSL branch if you want to try it out.

**Comment by morph1904** [comment]
Closing issue as not required. See Tyger2
