### ISSUE TITLE
TCP Server Type

### ISSUE THREAD

**Issue by andyjhall** [morph1904/TygerCaddy#112]
Any interest in adding support for the below?

https://caddyserver.com/docs/net
https://github.com/pieterlouw/caddy-net/blob/master/README.md

**Comment by morph1904** [comment]
Hi Andy, 

This would be good to add, the only issue i see is this part of the docs. 
`Start/Run
Note: When you start caddy you will need to specify the server type using the -type flag: caddy -type=net`

I do not know the impact on standard Proxy functionality when this is used. 

This will need looking into some more.

**Comment by morph1904** [comment]
Closing issue as not required. See Tyger2

We will not be implementing this feature in the near future. This would require running 2 instances of Caddy which is currently beyond the scope of this project.
