### ISSUE TITLE
Not working, fresh install

### ISSUE THREAD

**Issue by boscorelly** [morph1904/TygerCaddy#115]
Hi,

i have made a fresh isntall (on a debian), and nothing is working.
I get connexion refused after setting up host and proxy.

I haven't found any logs...

Any help is welcome :)

**Comment by morph1904** [comment]
Hi @boscorelly,

Sorry you are having issues. 

So you have gotten the TygerCaddy application working, but your host/proxy is not working is that right?

**Comment by morph1904** [comment]
Ok. that looks ok. can you please post the output of the below:

```service caddy status```

**Comment by boscorelly** [comment]
root@proxy:/apps/TygerCaddy/TygerCaddy# service caddy status
● caddy.service - Caddy HTTP/2 web server
   Loaded: loaded (/etc/systemd/system/caddy.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Mon 2018-08-06 18:03:39 CEST; 23min ago
     Docs: https://caddyserver.com/docs
  Process: 38376 ExecStart=/usr/local/bin/caddy -log /apps/TygerCaddy/TygerCaddy/data/logs/caddy.txt -agree=true -conf=/apps/TygerCaddy/TygerCaddy/data/cad
 Main PID: 38376 (code=exited, status=1/FAILURE)

août 06 18:03:31 proxy systemd[1]: Started Caddy HTTP/2 web server.
août 06 18:03:39 proxy systemd[1]: caddy.service: Main process exited, code=exited, status=1/FAILURE
août 06 18:03:39 proxy systemd[1]: caddy.service: Unit entered failed state.
août 06 18:03:39 proxy systemd[1]: caddy.service: Failed with result 'exit-code'.

**Comment by morph1904** [comment]
Ok So it is a problem with caddy. Sorry for this can you send the contents of /apps/TygerCaddy/TygerCaddy/data/logs/caddy.txt it may need cleaning.

**Comment by boscorelly** [comment]
.fr/gestion.solutek.fr.crt
2018/08/06 17:50:32 [INFO] acme: Registering account for team@solutek.fr
2018/08/06 17:50:33 [INFO][glpi.solutek.fr] acme: Obtaining bundled SAN certificate
2018/08/06 17:50:33 [INFO][glpi.solutek.fr] AuthURL: https://acme-v02.api.letsencrypt.org/acme/authz/HNTMl-vUt_0VKI7eCj-rGofTxoMD-RjrOj6-N-gpoZ8
2018/08/06 17:50:33 [INFO][glpi.solutek.fr] acme: Could not find solver for: tls-alpn-01
2018/08/06 17:50:33 [INFO][glpi.solutek.fr] acme: Could not find solver for: dns-01
2018/08/06 17:50:33 [INFO][glpi.solutek.fr] acme: Trying to solve HTTP-01
2018/08/06 17:55:46 [INFO][glpi.solutek.fr] acme: Obtaining bundled SAN certificate
2018/08/06 17:55:46 [INFO][glpi.solutek.fr] AuthURL: https://acme-v02.api.letsencrypt.org/acme/authz/OjbPdS8W_ZqT_jC2BNxBKxiTdzItFlH_mclt1LAHYLQ
2018/08/06 17:55:46 [INFO][glpi.solutek.fr] acme: Trying to solve HTTP-01
2018/08/06 17:59:24 [INFO][glpi.solutek.fr] acme: Obtaining bundled SAN certificate
2018/08/06 17:59:25 [INFO][glpi.solutek.fr] AuthURL: https://acme-v02.api.letsencrypt.org/acme/authz/xO8WbjOg6m6DuBdTEk0Vkn5ja_AxDGA_Ft_hjkYcxz8
2018/08/06 17:59:25 [INFO][glpi.solutek.fr] acme: Trying to solve HTTP-01
2018/08/06 18:03:31 [INFO][support.solutek.fr] acme: Obtaining bundled SAN certificate
2018/08/06 18:03:32 [INFO][support.solutek.fr] AuthURL: https://acme-v02.api.letsencrypt.org/acme/authz/rdrXNuLDlSbsC2J8azD4rVyHnC1dwtZV-6HrnfVKfsg
2018/08/06 18:03:32 [INFO][support.solutek.fr] acme: Could not find solver for: tls-alpn-01
2018/08/06 18:03:32 [INFO][support.solutek.fr] acme: Trying to solve HTTP-01
2018/08/06 18:03:33 [INFO][support.solutek.fr] Served key authentication
2018/08/06 18:03:37 [INFO][support.solutek.fr] The server validated our request
2018/08/06 18:03:37 [INFO][support.solutek.fr] acme: Validations succeeded; requesting certificates
2018/08/06 18:03:39 [INFO][support.solutek.fr] Server responded with a certificate.
2018/08/06 18:03:39 [INFO][support.solutek.fr] Certificate written to disk: /etc/ssl/caddy/acme/acme-v02.api.letsencrypt.org/sites/support.solutek.fr/support.solutek.fr.crt

**Comment by morph1904** [comment]
@boscorelly Thanks for that. The log looks good. We need to see why caddy is failing to start as it has been running successfully. It has even got your SSL certs for you. 

Is there anything in ```journalctl -xe``` that gives away why caddy is failing to start?

**Comment by morph1904** [comment]
It could be. I assume there is no reference to Caddy within those logs?

Caddy is acting as the reverse proxy server, and is clearly not running and so connections to port 80 and 443 are being refused. We just need to establish why caddy is now unable to run. 

it may be worth trying 

```service caddy start`` then ```journalctl -xe``` to see if there are any more clues.

**Comment by boscorelly** [comment]
août 07 09:16:08 proxy systemd[1]: Configuration file /etc/systemd/system/caddy-reload.path is marked executable. Please remove executable permission bits. Proceeding anyway.
août 07 09:16:08 proxy systemd[1]: Configuration file /etc/systemd/system/uwsgi.service is marked executable. Please remove executable permission bits. Proceeding anyway.
août 07 09:16:08 proxy systemd[1]: Configuration file /etc/systemd/system/caddy.service is marked executable. Please remove executable permission bits. Proceeding anyway.
août 07 09:16:08 proxy systemd[1]: Configuration file /etc/systemd/system/caddy-reload.service is marked executable. Please remove executable permission bits. Proceeding anyway.
août 07 09:16:09 proxy systemd[1]: Network Service is not active.
août 07 09:16:09 proxy systemd[1]: Dependency failed for Wait for Network to be Configured.
-- Subject: L'unité (unit) systemd-networkd-wait-online.service a échoué
-- Defined-By: systemd
-- Support: https://www.debian.org/support
--
-- L'unité (unit) systemd-networkd-wait-online.service a échoué, avec le résultat dependency.
août 07 09:16:09 proxy systemd[1]: systemd-networkd-wait-online.service: Job systemd-networkd-wait-online.service/start failed with result 'dependency'.
août 07 09:16:09 proxy systemd[1]: Started Caddy HTTP/2 web server.
-- Subject: L'unité (unit) caddy.service a terminé son démarrage
-- Defined-By: systemd
-- Support: https://www.debian.org/support
--
-- L'unité (unit) caddy.service a terminé son démarrage, avec le résultat done.
août 07 09:16:09 proxy caddy[1044]: Activating privacy features... done.
août 07 09:16:09 proxy caddy[1044]: time: missing unit in duration 60
août 07 09:16:09 proxy systemd[1]: caddy.service: Main process exited, code=exited, status=1/FAILURE
août 07 09:16:09 proxy systemd[1]: caddy.service: Unit entered failed state.
août 07 09:16:09 proxy systemd[1]: caddy.service: Failed with result 'exit-code'.


Hum, i see an error :D

**Comment by morph1904** [comment]
I see potentially 2 :) 

So the first is a network dependency. The second is this: 

'''août 07 09:16:09 proxy caddy[1044]: time: missing unit in duration 60'''

Is this a VM or baremetal?

**Comment by morph1904** [comment]
Have you set up some sort of NTP service? Also have you ensured that your network connections are setup and working prior to installing TygerCaddy?

**Comment by boscorelly** [comment]
I haven't installed or configured any ntp service.

internet is ok : i can update and upgrade the VM

root@proxy:/home/coe# ifconfig
eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.254.253  netmask 255.255.255.0  broadcast 192.168.254.255
        inet6 fe80::215:5dff:fefe:c810  prefixlen 64  scopeid 0x20<link>
        ether 00:15:5d:fe:c8:10  txqueuelen 1000  (Ethernet)
        RX packets 9990059  bytes 14253063511 (13.2 GiB)
        RX errors 0  dropped 298  overruns 0  frame 0
        TX packets 835  bytes 124393 (121.4 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

**Comment by morph1904** [comment]
Ok. One thing to try. Please remove the below options from the proxy save it then try restarting caddy. 
fail_timeout 60
max_fails 10
max_conns 100
try_duration 30
try_interval 2
timeout 300

**Comment by morph1904** [comment]
Caddy should hot reload after modifying hosts. 

I will do some more investigation on your issue and get back to you  when I know some more.

**Comment by boscorelly** [comment]
Thanks !

**Comment by morph1904** [comment]
@boscorelly what branch were you using is it master?

**Comment by boscorelly** [comment]
Yes, master branch !

I have another issue : i am proxying exchange an when it comes to autodiscover, i have a 502 Bad Gateway for https://autodiscover.domain.tld/autodiscover/autodiscover.xml and it makes outlook unable to work with Outlook Anywhere.
On my iphone, an expired certificate is presented : 
www.weebly.com
delivered by geotrust
not reliable
expired 03 august 2018 14:00

**Comment by boscorelly** [comment]
error found !

07/Aug/2018:17:40:33 +0200 [ERROR 502 /Autodiscover/Autodiscover.xml] stream error: stream ID 3; HTTP_1_1_REQUIRED

**Comment by boscorelly** [comment]
Same problem as here : https://social.technet.microsoft.com/Forums/office/en-US/4fea485e-5494-439e-b680-f5ef876c8dd0/exchange-2013-autodiscover-fails-when-proxing-through-iis-arr-25?forum=exchangesvrgeneral

The autodiscover process is a login challenge. If the client get a 401 it convert it to 502 bad gateway. Disabling windows challenge make prompt coming.

**Comment by morph1904** [comment]
@boscorelly 

I am not really an exchange expert. Did you install the fix suggested on that thread? ```have you tried the following hotfix: http://www.microsoft.com/en-us/download/details.aspx?id=30333```

This does not look like it is a TygerCaddy issue.

**Comment by boscorelly** [comment]
i'm on IIS 10 (server 2016) and arr is not installed on endpoint.

When i disable Windows auth, i have the prompt for the credential. Otherwise, the first 401 error is interpreted as a 502 bad gateway error.

Is it possible the http.forwardproxy will help ?

**Comment by morph1904** [comment]
I am not sure as I haven't really tried using that module in Caddy. 

I haven't got a testbed for this and would need more information to see if there are any options in TygerCaddy that could help you. 

I am keen to get this working for you. 

Maybe we could arrange an online meet to look at it further?

**Comment by boscorelly** [comment]
Hi,

i have searched and the problem is the same as nginx : caddy is not abble to handle this type of connection. I have to use HAproxy, it's the only way to achieve this.

Thanks for your help !
