### ISSUE TITLE
Request: LetsEncrypt Wildcard support

### ISSUE THREAD

**Issue by derek-shnosh** [morph1904/TygerCaddy#117]
I'd like to use TygerCaddy to host numerous sites behind the same TLD with a single wildcard cert.

**Comment by morph1904** [comment]
Hi Derek.

We are looking into this however it requires the dns challenge to be setup
which is currently problematic for us.

See this excerpt from caddy.

Wildcard certificates
Caddy can obtain and manage wildcard certificates when it is configured to
serve a site with a qualifying wildcard name. A site name qualifies for a
wildcard if only its left-most domain label is a wildcard. For example, *.
example.com qualifies, but these do not: sub.*.example.com, foo*.example.com,
*bar.example.com, *.*.example.com, etc. To get a wildcard, you simply need
to enable the DNS challenge (described below; it's very easy). We recommend
using wildcards only when you have so many subdomains that you would
encounter CA rate limits trying to obtain certificates for them all. If you
have many subdomains configured differently in your Caddyfile, you can also
force a wildcard for them by using the wildcard subdirective of the tls
directive.

Regards
Morph1904

**Comment by morph1904** [comment]
Closing issue as not required. See Tyger2
