### ISSUE TITLE
redirects to local IP

### ISSUE THREAD

**Issue by aporzio1** [morph1904/TygerCaddy#131]
I have Wordpress running and the `site.example.com` loads (although the CSS is messed up but that could be cloud flare) but if I try to go to `site.example.com/wp-admin` it redirects to the local `192.x.x.x` address instead.

**Comment by arevindh** [comment]
Most probably its a problem from WordPress.
Try setting the Site and homepage settings on WordPress to https://site.example.com/

**Comment by aporzio1** [comment]
it also does it for Plex. @arevindh I have Plex.example.com that redirects to 192.x.x.x

**Comment by arevindh** [comment]
Did you try enabling **Transparent** option on proxy ?

![transparent](https://user-images.githubusercontent.com/693151/63653014-ec904880-c784-11e9-81ee-7e969080d53a.jpg)

**Comment by arevindh** [comment]
@aporzio1 Any updates?

**Comment by morph1904** [comment]
@aporzio1. I will soon be archiving this repo as we have started the Beta of tyger2. I recommend moving to Tyger2 if possible. The new repo can be found at https://github.com/morph1904/Tyger2.
