### ISSUE TITLE
JQuery Tag-It for hostname field

### ISSUE THREAD

**Issue by arevindh** [morph1904/TygerCaddy#2]
![JQuery Tag-it](https://user-images.githubusercontent.com/693151/39749979-ab6c1d4e-52d1-11e8-90df-93894f299cff.png)

Library url : http://aehlke.github.io/tag-it/

**Comment by morph1904** [comment]
I may not use this specific library but I can look at something similar. 

What are you looking to gain with this? Are you wanting to assign multiple addresses to a single proxy location using only one form?

**Comment by arevindh** [comment]
It will help in assigning multiple hostname to same proxy address

**Comment by morph1904** [comment]
Ok I will look into this in the first enhancement pack. I will work on issues first and come back to this.

**Comment by arevindh** [comment]
Awesome

**Comment by morph1904** [comment]
Closing issue as not required. See Tyger2
