### ISSUE TITLE
Unable to access UI after adding domain 

### ISSUE THREAD

**Issue by arevindh** [morph1904/TygerCaddy#3]
UI shows No such site at :80 after adding deleting or editing a host.

**From service status** 

```
2018/05/08 17:41:04 [INFO] SIGUSR1: Reloading
2018/05/08 17:41:04 [INFO] Reloading
2018/05/08 17:41:04 [WARNING] TLS disabled for
[INFO] Reloading complete
[INFO] 10.0.7.8 - No such site at :80 (Remote: 10.8.0.4, Referer: http://10.0.7.8/hosts/delete/5/)
```

**Comment by morph1904** [comment]
Looking at this I have a few ways to go with this. 

1. I can remove the default caddyfile entry to the dashboard, meaning you have to access the panel via port 9090 (http://myipaddr:9090) unless you add a proxy entry in the hosts lists. 

2. I can keep the default caddyfile entry and provide you with the ability to set the default hostname and port. (The application will still run on port 9090 in the backend)

Any feedback on this? What would you prefer?

**Comment by arevindh** [comment]
I think it is better to have a fixed port. If the user needs to access it publicly they can always make a host entry proxying to that port.
One more suggestion: Allow only connections to GUI from private IP ranges by default

**Comment by morph1904** [comment]
#4 
This should now be fixed. Please test and reply with results when able.

**Comment by arevindh** [comment]
Thanks , its fixed
