### ISSUE TITLE
Docker requires empty directories for config files. Needed for persistence

### ISSUE THREAD

**Issue by sparky8251** [morph1904/TygerCaddy#46]
Docker persistence requires that relevant unique files like the certificates and
db.sqlite3 file exist OUTSIDE the container. That way if the container is deleted
your config files aren't deleted. To update a container you have to delete the old one (for a reason why this is needed).

To do this, when a docker container is run you can specify volumes like so:

-v /data/docker/TygerCaddy/data:/apps/TygerCaddy/TygerCaddy

That mounts the containers /apps/TygerCaddy/TygerCaddy at /data/docker/TygerCaddy/data
on the docker host.

The issue is that docker will map over the containers directory. For example,
if on my docker host the /data/docker/TygerCaddy/data directory is empty 
(since its a first run/container only install) when I map the above volume, 
the /apps/TygerCaddy/TygerCaddy is now empty INSIDE the container. 
Can't run the program without any of its files!

I also can't map a file this way. It has to be directories, so no mapping the db.sqlite3 file directly.

Changes to the project structure need to be made so that important files have their own empty folders to live in.

**Comment by morph1904** [comment]
#51 Major Update Should fix this.

**Comment by sparky8251** [comment]
It indeed has! Closing this issue. 

Thanks for the efforts!
