### ISSUE TITLE
Uninstall script

### ISSUE THREAD

**Issue by JourneyOver** [morph1904/TygerCaddy#6]
Just making a note of this from the reddit thread asking about uninstalling.. I'd like to see this as well since my reasoning is that until I can get a new modem I can't port forward due to comcast shoddy modem/router combo so I am just seeing tygercaddy as wasted spaced right now since I dunno when exactly I'll be able to get a new modem :/

**Comment by JourneyOver** [comment]
@morph1904 I see this issue is now closed, but I don't see an uninstall script anywhere? :o all I see are the install script and the update script

**Comment by morph1904** [comment]
Hi JourneyOver, 
This was my mistake, I included it in the commit notes but forgot to add the file to the commit. I did successfully add it about 20 mins ago though. 

Here is the link directly to the script. 
https://raw.githubusercontent.com/morph1904/TygerCaddy/master/tyger-uninstall-ubuntu.sh
Instructions:

- SSH on to server
- cd /tmp
- nano uninstall.sh
- copy the contents of the uninstall script and save. 
- bash uninstall.sh or . uninstall.sh

hope this helps, and sorry for the confusion.

**Comment by JourneyOver** [comment]
@morph1904 It's all good :p and yep already done all that, only thing that I ran into in the uninstall script is when it got to the `apt remove -y uwsgi` it threw a message that uwsgi wasn't installed, so I dunno what was up with that since well the install and update script both install it >.<

**Comment by JourneyOver** [comment]
tell me about it, anyways it doesn't seem like it had any adverse affects either way from what I can tell and searching around I can't seem to find anything pointing to uwsgi so I guess either way it's removed.

**Comment by hank** [comment]
Just found this - can you add it to the wiki or something?
