### ISSUE TITLE
DNS verification option

### ISSUE THREAD

**Issue by aleeyoop** [morph1904/TygerCaddy#7]
if you could add DNS verification option for letsencrypt that would be amazing.
In my case my ISP doesnt let me open port 80 so I can't obtain a cert that way.
Thank you

**Comment by morph1904** [comment]
Hi aleeyoop, I will hopefully sort this very soon. 

My next task is to add a bunch of features to the proxy config set and the SSL config set. I will keep you updated.

**Comment by morph1904** [comment]
Hi @aleeyoop 

This functionality should work for you, unfortunately i am not able to test comprehensively. Please let me know if this works for you. 

This will require a new install, simply delete the apps directory and re-run the install script, I am afraid you will need to input your hosts again.

**Comment by morph1904** [comment]
Closing issue as not required. See Tyger2
