### ISSUE TITLE
Option for adding extra headers such as HSTS

### ISSUE THREAD

**Issue by arevindh** [morph1904/TygerCaddy#8]
It would be nice to have an option to add extra headers.
We could add `header / Strict-Transport-Security "max-age=31536000;"` to  force HTTP Strict Transport Security

**Comment by morph1904** [comment]
I will be looking at adding some more reverse proxy features in the next release. Will keep you posted.

**Comment by sparky8251** [comment]
Headers released. If you encounter bugs when using please open a new issue.
