### ISSUE TITLE
Add LDAP authentication

### ISSUE THREAD

**Issue by sparky8251** [morph1904/TygerCaddy#83]
It'd be nice to have on less username/password to remember. LDAP authentication is very nice for even small home labs like the one I run.

**Comment by Strider3000** [comment]
LDAP may prompt a re-think of authorizations. I believe there is only one account type for TygerCaddy currently - admin (god-mode). If you add LDAP you could just allow a successful set of privileges to have admin access, or require membership in a specific group to have admin access. But what if you want to restructure TC in the future to allow different authorizations to manage different sub domains? Plus when someone eventually asks for RADIUS integration for 2factor support, how would that work with user access permissions?

**Comment by morph1904** [comment]
@Strider3000 

I am still looking into this. I think it is likely that we will look at the ability to set up permissions groups inside TygerCaddy this would set the ability to map either domains, proxies or permission sets to a permission group. This would then allow an admin to set what directory group would have which permission group. 

TygerCaddy is not really intended for use in side a large scale commercial/professional environment that would rely heavily on LDAP/AD for permissions management. It is likely that the professionals in that kind of environment would be comfortable with NGINX configs or have enough IPs not to use a reverse proxy. 

We are currently focussing on the new API build. This will allow for more integrations and the ability to easily look at future authentication types.

**Comment by morph1904** [comment]
Closing issue as not required. See Tyger2
