### ISSUE TITLE
Install script not working

### ISSUE THREAD

**Issue by gannon145** [morph1904/TygerCaddy#85]
Tired running the install script and get he following:

I also had to run chmod +x before I could even attempt to run.

#:/tmp$ sudo /tmp/tyger-install-ubuntu.sh
/bin/sh: 0: Can't open bash

OS: Ubuntu 16.04.3 fresh install

**Comment by arevindh** [comment]
try 
`sudo bash /tmp/tyger-install-ubuntu.sh`

**Comment by gannon145** [comment]
Worked. Thank you!
