### ISSUE TITLE
502 Bad Gateway - After script install

### ISSUE THREAD

**Issue by gannon145** [morph1904/TygerCaddy#87]
Got the install script to work using;

#: sudo bash /tmp/tyger-install-ubuntu.sh

After install completes, I'm getting a 502 Bad Gateway.
Tried Chrome and IE, cleared cache, restarted server.

Thanks for any ideas.

**Comment by gannon145** [comment]
Negative.

**Comment by morph1904** [comment]
What is the output of service uwsgi status?

**Comment by morph1904** [comment]
Ok. It seems to be running ok, can you try service uwsgi restart anyway please? Then try access the http://your-ip:9090 again.

**Comment by morph1904** [comment]
ok that is odd. uWSGI is serving the dashboard and caddy is listening correctly. What is the result of the following? lsof -i :9090

**Comment by gannon145** [comment]
:~$ sudo lsof -i :9090
COMMAND   PID USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
uwsgi   20678 root    8u  IPv4  65595      0t0  TCP *:9090 (LISTEN)
uwsgi   20690 root    8u  IPv4  65595      0t0  TCP *:9090 (LISTEN)

**Comment by morph1904** [comment]
The port for the dash is set in the uwsgi.ini file and caddy's settings are kept in the above caddyfile.conf

**Comment by gannon145** [comment]
Do you get a connection refused error? No, just "ERR_EMPTY_RESPONSE"
Do you have a firewall blocking port 9090? Already added an allow rule to windows firewall
Are you using Ubuntu 16.04? 16.04.3
Have you tried sudo ufw allow 9090? Yea already tried it.

**Comment by morph1904** [comment]
Ok the error empty response is what we needed here. 

An empty response is still a response so we know now that the dashboard does not have a connection issue but an issue responding to the request. 

Please can you try the following URL

http://your-server-ip:9090/install/

**Comment by gannon145** [comment]
Still ERR_EMPTY_RESPONSE

**Comment by morph1904** [comment]
Ok. it looks like you have all of the pre-req services but the dashboard itself has an issue. As you have not completed the install yet i think the best thing to do is "re-install" the best way to do this is to delete the /apps directory and all of its contents, then re-run the installer. It will be much quicker because it will not re-install uwsgi or caddy etc.

**Comment by gannon145** [comment]
Ok, I'll have to do that later. I'll reply here when I've done that and the result. Thanks for the help!

**Comment by morph1904** [comment]
No problem, in the meantime, i am going to do another brand new install with the master branch and see if i can replicate your issue. Thanks for sticking with us, it will be great once we get it working for you I promise :)

**Comment by gannon145** [comment]
I'm running in VM, so if we want to rebuild on a specific image I can do that. Thanks again.

**Comment by gannon145** [comment]
Ok, so decided to change it up and try installing in a LXC to see what happened. Worked perfect. Unfortunately I don't want to run TygerCaddy in a container, so I'll see need to figure out what is happening.

Is Ubuntu LAMP fresh install required or bare install?

**Comment by morph1904** [comment]
I'm running a basic 16.04.4 Ubuntu Server install. I installed on a clean vm earlier and it worked perfectly. I am not sure where your issue is at the moment. Have you tried what i suggested?

**Comment by gannon145** [comment]
Fresh 16.04.3 install and it worked perfectly. No clue what the problem was before. Thanks for you help.

**Comment by morph1904** [comment]
No problem. Glad you're up and running. Give us a shout if you need any support. We are still early days yet but leaps and bounds in the last week alone.
