### ISSUE TITLE
Configuration Guide

### ISSUE THREAD

**Issue by gannon145** [morph1904/TygerCaddy#89]
I know you guys are just getting this project started, but I would recommend you put a basic configuration guide together. It will help with new user adoption and reduce tickets caused by mis-configuration. I know it's not rocket science, but just a basic walk through would probably go a long way.

**Comment by morph1904** [comment]
Hi @gannon145, 

We now have a basic wiki page up which should hopefully address this. We will of course be trying to keep on top of this in future. If you have any suggestions for amendments to the documentation or any additions please let us know. 

You can view the page here: [Quick Start Guide](https://github.com/morph1904/TygerCaddy/wiki)

I will now close this. 

Lee
