### ISSUE TITLE
Any plans for a Docker version?

### ISSUE THREAD

**Issue by LarsNorgaard** [morph1904/TygerCaddy#9]
Would be super nice with a docker version of this, both for arm and x86.

**Comment by morph1904** [comment]
I am not a docker expert but I am talking with someone who may be able to help with this. I will keep you all posted.

**Comment by sparky8251** [comment]
I added initial support for Docker on x86_x64 devices. The project needs a few changes to enable persistence and these are being explored. Its functional if you build it yourself with the included instructions, I just can't recommend it right now.

Once persistence comes around I have some ARM devices and will add ARM support around that time.

**Comment by sparky8251** [comment]
Docker persistence added. Docker support on x86 _x64 should be fully implemented. ARMHF will come shortly.

View the README included in the docker folder for examples.

STRONGLY recommend exposing the volumes mentioned in the example command. Let's Encrypt has rate limits and they are easy to hit if you rerun the container a few times.

**Comment by sparky8251** [comment]
Docker finally fully functional.

Apologize if you tried it before the latest release.
