### ISSUE TITLE
Error adding host

### ISSUE THREAD

**Issue by andyjhall** [morph1904/TygerCaddy#95]
Request Method: | POST
-- | --
http://proxy/hosts/add/
2.0.3
AttributeError
'NoneType' object has no attribute 'id'
./hosts/caddyfile.py in generate_caddyfile, line 34
/usr/local/bin/uwsgi
3.6.5
['.',  '',  '/usr/lib/python36.zip',  '/usr/lib/python3.6',  '/usr/lib/python3.6/lib-dynload',  '/usr/local/lib/python3.6/dist-packages',  '/usr/lib/python3/dist-packages']
Wed, 23 May 2018 17:27:01 +0100

**Comment by andyjhall** [comment]
This is a fresh setup, I assumed the first thing I needed to do was setup a host as this is on the dashboard when you login, nothing else has been setup yet

**Comment by andyjhall** [comment]
Ok i've updated to Alpha 0.2, however if I try to create a host first i still get the below error. Does this need some error handling to stop users creating a Host with no proxy?

Request Method: | POST
-- | --
http://proxy/hosts/add/
2.0.3
KeyError
'dns_verification'
./hosts/views.py in form_valid, line 25
/usr/local/bin/uwsgi
3.6.5
['.',  '',  '/usr/lib/python36.zip',  '/usr/lib/python3.6',  '/usr/lib/python3.6/lib-dynload',  '/usr/local/lib/python3.6/dist-packages',  '/usr/lib/python3/dist-packages']
Thu, 24 May 2018 10:23:34 +0100

This then breaks the "All Hosts" screen with the below error:


Request Method: | GET
-- | --
http://proxy/hosts/list/
2.0.3
NoReverseMatch
Reverse for 'update-proxy' with arguments '('',)' not found. 1 pattern(s) tried: ['proxies\\/update\\/(?P<pk>[0-9]+)\\/$']
/usr/local/lib/python3.6/dist-packages/django/urls/resolvers.py in _reverse_with_prefix, line 632
/usr/local/bin/uwsgi
3.6.5
['.',  '',  '/usr/lib/python36.zip',  '/usr/lib/python3.6',  '/usr/lib/python3.6/lib-dynload',  '/usr/local/lib/python3.6/dist-packages',  '/usr/lib/python3/dist-packages']
Thu, 24 May 2018 10:25:43 +0100

Do you still need the above logs?

**Comment by morph1904** [comment]
Hi.

You spotted a bug in the hosts adding process which I have now fixed. You can pull alpha 0.2 again and you will no longer get this error. 

There should be some checking preventing you from saving a host without a proxy but this is obviously not working. I will push another fix for this later today. 

Thanks for posting g this it is very helpful. I do not need to see any other logs for now. 

Lee

**Comment by morph1904** [comment]
I just had another quick look at the issue with the creation of Hosts before a Proxy and it is an error in the DB schema. I am not currently in a position to fix this for another 6 hours or so, but will do as soon as I can.

**Comment by andyjhall** [comment]
Not sure whats happened but now the caddy service wont start after a fresh install, ive just wiped out my vm and rebuilt it and still caddy wont boot with the below errors coming from "service caddy status"

root@proxy:/apps/TygerCaddy/TygerCaddy# service caddy status
● caddy.service - Caddy HTTP/2 web server
   Loaded: loaded (/etc/systemd/system/caddy.service; enabled; vendor preset: en
   Active: failed (Result: resources) since Thu 2018-05-24 11:43:42 UTC; 4min 54
     Docs: https://caddyserver.com/docs

May 24 11:43:42 proxy systemd[1]: caddy.service: Failed to load environment file
May 24 11:43:42 proxy systemd[1]: caddy.service: Failed to run 'start' task: No
May 24 11:43:42 proxy systemd[1]: caddy.service: Failed with result 'resources'.
May 24 11:43:42 proxy systemd[1]: Failed to start Caddy HTTP/2 web server.
May 24 11:43:42 proxy systemd[1]: caddy.service: Service hold-off time over, sch
May 24 11:43:42 proxy systemd[1]: caddy.service: Scheduled restart job, restart
May 24 11:43:42 proxy systemd[1]: Stopped Caddy HTTP/2 web server.
May 24 11:43:42 proxy systemd[1]: caddy.service: Start request repeated too quic
May 24 11:43:42 proxy systemd[1]: caddy.service: Failed with result 'resources'.
May 24 11:43:42 proxy systemd[1]: Failed to start Caddy HTTP/2 web server.
lines 1-15/15 (END)...skipping...
● caddy.service - Caddy HTTP/2 web server
   Loaded: loaded (/etc/systemd/system/caddy.service; enabled; vendor preset: enabled)
   Active: failed (Result: resources) since Thu 2018-05-24 11:43:42 UTC; 4min 54s ago
     Docs: https://caddyserver.com/docs

May 24 11:43:42 proxy systemd[1]: caddy.service: Failed to load environment files: No such file or directory
May 24 11:43:42 proxy systemd[1]: caddy.service: Failed to run 'start' task: No such file or directory
May 24 11:43:42 proxy systemd[1]: caddy.service: Failed with result 'resources'.
May 24 11:43:42 proxy systemd[1]: Failed to start Caddy HTTP/2 web server.
May 24 11:43:42 proxy systemd[1]: caddy.service: Service hold-off time over, scheduling restart.
May 24 11:43:42 proxy systemd[1]: caddy.service: Scheduled restart job, restart counter is at 5.
May 24 11:43:42 proxy systemd[1]: Stopped Caddy HTTP/2 web server.
May 24 11:43:42 proxy systemd[1]: caddy.service: Start request repeated too quickly.
May 24 11:43:42 proxy systemd[1]: caddy.service: Failed with result 'resources'.
May 24 11:43:42 proxy systemd[1]: Failed to start Caddy HTTP/2 web server.

**Comment by andyjhall** [comment]
Adding a host (after adding a proxy) now gives this error.
![capture](https://user-images.githubusercontent.com/989064/40490979-dbd0fc4e-5f64-11e8-884c-69877438b795.PNG)

**Comment by morph1904** [comment]
@andyjhall. I will get this fixed in the next couple of hours and complete a full test. I appreciate you sticking with us. These issues will be fixed today.

**Comment by andyjhall** [comment]
Confirmed, this is now fixed. Thanks.
